export const PROJECTS = [
  {
    title: 'Tatabányai Ultrahang Centrum',
    link: 'https://www.tatabanyaultrahang.eu',
    description:
      'Marketing website for Tatabányai Ultrahang Centrum. Built with TypeScript, Next.js, Tailwind CSS, and shadcn/ui.',
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS', 'shadcn/ui', 'Vercel'],
  },
  {
    title: 'BABA Construction Corp.',
    link: 'https://www.babaconstructioncorp.com/',
    description:
      'Marketing website for BABA Construction Corp. Built with TypeScript, Next.js, Tailwind CSS, shadcn/ui, React Hook Form, and Upstash Redis for rate limiting.',
    tags: [
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'shadcn/ui',
      'React Hook Form',
      'Zod',
      'Upstash',
      'Redis',
      'Vercel',
    ],
  },
  {
    title: 'REGALE Energy Zrt.',
    link: 'https://www.regale.hu',
    description:
      'Marketing website and admin dashboard for REGALE Energy Zrt. Built with Rust, TypeScript, Next.js, Tailwind CSS, MySQL and Upstash Redis for rate limiting.',
    tags: [
      'Rust',
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'Headless UI',
      'React Hook Form',
      'Zod',
      'Auth.js',
      'Amazon SES',
      'lettre',
      'MySQL',
      'Prisma',
      'sqlx',
      'Aiven',
      'Vercel',
      'AWS Lambda',
    ],
  },
  {
    title: 'Frontend Mentor',
    link: 'https://www.frontendmentor.io/profile/stay-js',
    description:
      'Frontend Mentor offers invaluable real-world web development challenges, to sharpen HTML, CSS, and JavaScript skills.',
    tags: ['JavaScript', 'TypeScript', 'Next.js', 'Astro', 'Tailwind CSS', 'Headless UI'],
  },
  {
    title: 'JobKeeper',
    link: 'https://job-keeper.znagy.hu',
    description:
      'A powerful dashboard for managing all your jobs, tracking positions, and monitoring earnings. Built with TypeScript, Next.js, Tailwind CSS, shadcn/ui, React Hook Form, Clerk, tRPC, Drizzle and MySQL.',
    tags: [
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'shadcn/ui',
      'React Hook Form',
      'Zod',
      'Clerk',
      'tRPC',
      'Drizzle',
      'MySQL',
      'Aiven',
      'Vercel',
    ],
  },
  {
    title: 'Flashcards App',
    link: 'https://flashcards.znagy.hu',
    description:
      'Quizlet-like flashcard app with GitHub authentication. Built with TypeScript, Next.js, Tailwind CSS, Headless UI, React Hook Form, tRPC, Prisma and MySQL.',
    tags: [
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'Headless UI',
      'React Hook Form',
      'Zod',
      'tRPC',
      'Auth.js',
      'MySQL',
      'Prisma',
      'Aiven',
      'Vercel',
    ],
  },
  {
    title: 'Todo App',
    link: 'https://todo.znagy.hu',
    description:
      'Todo app with GitHub authentication. Built with TypeScript, Next.js, Tailwind CSS, Headless UI, tRPC, Prisma, MySQL, and Upstash Redis for rate limiting.',
    tags: [
      'TypeScript',
      'Next.js',
      'Tailwind CSS',
      'Headless UI',
      'Zod',
      'tRPC',
      'Auth.js',
      'MySQL',
      'Prisma',
      'Aiven',
      'Vercel',
    ],
  },
  {
    title: 'Stay Random',
    link: 'https://random.znagy.hu',
    description:
      'Random generator for CUIDs, GUIDs, UUIDs, numbers, colors, and more. Built with Next.js and Tailwind CSS.',
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS', 'Vercel'],
  },
] as const;
