export const SKILLS = [
  {
    title: 'Languages & Libraries',
    skills: [
      'JavaScript',
      'TypeScript',
      'Rust',
      'C#',
      '.NET',
      'Python',
      'PHP',
      'React',
      'Next.js',
      'Auth.js',
      'React Query',
      'Astro',
      'Vite',
      'Vue',
      'tRPC',
      'Prisma',
      'Drizzle',
      'Express.js',
    ],
  },
  {
    title: 'Styling & UI',
    skills: [
      'Tailwind CSS',
      'Headless UI',
      'Radix UI',
      'shadcn/ui',
      'Mantine',
      'Bootstrap',
      'Sass/SCSS',
      'CSS3',
      'HTML5',
    ],
  },
  {
    title: 'Technologies',
    skills: [
      'Node.js',
      'NPM',
      'PNPM',
      'Yarn',
      'Bun',
      'MongoDB',
      'MySQL',
      'PostgreSQL',
      'Redis',
      'Docker',
      'nginx',
      'Git',
      'GitHub',
      'GitLab',
      'GitHub CI/CD',
    ],
  },
  {
    title: 'Platforms & Cloud',
    skills: [
      'Vercel',
      'Netlify',
      'PlanetScale',
      'Upstash',
      'Aiven',
      'Railway',
      'DigitalOcean',
      'Linode',
      'Heroku',
      'Render',
      'Cloudflare',
      'AWS Services',
      'Serverless Framework',
      'Clerk',
    ],
  },
] as const;
